module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Users', [{
      username: 'Muller',
      email: 'test1@test.ru',
      password: '12345678',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      username: 'Wagner',
      email: 'test2@test.ru',
      password: '12345678',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      username: 'Richter',
      email: 'test3@test.ru',
      password: '12345678',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      username: 'Noskov',
      email: 'test4@test.ru',
      password: '12345678',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      username: 'Hoffman',
      email: 'test5@test.ru',
      password: '12345678',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      username: 'Stepan',
      email: 'test6@test.ru',
      password: '12345678',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      username: 'Nurali',
      email: 'test7@test.ru',
      password: '12345678',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      username: 'Helmit',
      email: 'test8@test.ru',
      password: '12345678',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      username: 'Monica',
      email: 'test9@test.ru',
      password: '12345678',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      username: 'Cathrin',
      email: 'test10@test.ru',
      password: '12345678',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      username: 'Andreas',
      email: 'test11@test.ru',
      password: '12345678',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      username: 'Claudia',
      email: 'test12@test.ru',
      password: '12345678',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      username: 'Birgit',
      email: 'test13@test.ru',
      password: '12345678',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      username: 'Mikoshka',
      email: 'test14@test.ru',
      password: '12345678',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      username: 'Butilka',
      email: 'test15@test.ru',
      password: '12345678',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      username: 'VkusVill',
      email: 'test16@test.ru',
      password: '12345678',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      username: 'Yuzu',
      email: 'test17@test.ru',
      password: '12345678',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      username: 'Lukas',
      email: 'test18@test.ru',
      password: '12345678',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      username: 'Mitrosha',
      email: 'test19@test.ru',
      password: '12345678',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      username: 'Asami',
      email: 'test20@test.ru',
      password: '12345678',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      username: 'Nina',
      email: 'test21@test.ru',
      password: '12345678',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      username: 'Noelle',
      email: 'test22@test.ru',
      password: '12345678',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      username: 'Matis',
      email: 'test23@test.ru',
      password: '12345678',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      username: 'Uwe',
      email: 'test24@test.ru',
      password: '12345678',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      username: 'Barbara',
      email: 'test25@test.ru',
      password: '12345678',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      username: 'Ursula',
      email: 'test26@test.ru',
      password: '12345678',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      username: 'Susanne',
      email: 'test27@test.ru',
      password: '12345678',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      username: 'Heike',
      email: 'test28@test.ru',
      password: '12345678',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      username: 'Gabriele',
      email: 'test29@test.ru',
      password: '12345678',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      username: 'Agata',
      email: 'test30@test.ru',
      password: '12345678',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      username: 'Cristobal',
      email: 'test31@test.ru',
      password: '12345678',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      username: 'Crispo',
      email: 'test32@test.ru',
      password: '12345678',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      username: 'Daniel',
      email: 'test33@test.ru',
      password: '12345678',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      username: 'Genovevo',
      email: 'test34@test.ru',
      password: '12345678',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      username: 'Gozos',
      email: 'test35@test.ru',
      password: '12345678',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      username: 'Heladio',
      email: 'test36@test.ru',
      password: '12345678',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      username: 'Honorata',
      email: 'test37@test.ru',
      password: '12345678',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      username: 'Lazaro',
      email: 'test38@test.ru',
      password: '12345678',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      username: 'Magdo',
      email: 'test39@test.ru',
      password: '12345678',
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      username: 'Marga',
      email: 'test40@test.ru',
      password: '12345678',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    ], {});
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Users', null, {});
  },
};
