module.exports = {
  async up(queryInterface) {
    await queryInterface.bulkInsert('Weapons', [{
      title: 'Kalash',
      ATK: 16,
      DEF: 13,
      quality: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      title: 'Kalash',
      ATK: 22,
      DEF: 15,
      quality: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      title: 'Kalash',
      ATK: 38,
      DEF: 29,
      quality: 3,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      title: 'Kalash',
      ATK: 68,
      DEF: 59,
      quality: 4,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      title: 'Kalash',
      ATK: 89,
      DEF: 77,
      quality: 5,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      title: 'Katana',
      ATK: 19,
      DEF: 5,
      quality: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      title: 'Katana',
      ATK: 27,
      DEF: 11,
      quality: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      title: 'Katana',
      ATK: 46,
      DEF: 31,
      quality: 3,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      title: 'Katana',
      ATK: 73,
      DEF: 53,
      quality: 4,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      title: 'Katana',
      ATK: 94,
      DEF: 66,
      quality: 5,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      title: 'Shield',
      ATK: 0,
      DEF: 19,
      quality: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      title: 'Shield',
      ATK: 0,
      DEF: 27,
      quality: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      title: 'Shield',
      ATK: 0,
      DEF: 46,
      quality: 3,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      title: 'Shield',
      ATK: 0,
      DEF: 75,
      quality: 4,
      createdAt: new Date(),
      updatedAt: new Date(),
    }, {
      title: 'Shield',
      ATK: 0,
      DEF: 94,
      quality: 5,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Knife',
      ATK: 7,
      DEF: 7,
      quality: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Knife',
      ATK: 11,
      DEF: 9,
      quality: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Knife',
      ATK: 12,
      DEF: 11,
      quality: 3,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Knife',
      ATK: 16,
      DEF: 15,
      quality: 4,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Knife',
      ATK: 20,
      DEF: 20,
      quality: 5,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Guitar',
      ATK: 4,
      DEF: 5,
      quality: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Guitar',
      ATK: 6,
      DEF: 8,
      quality: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Guitar',
      ATK: 9,
      DEF: 11,
      quality: 3,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Guitar',
      ATK: 12,
      DEF: 12,
      quality: 4,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Guitar',
      ATK: 14,
      DEF: 15,
      quality: 5,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Сhainsaw',
      ATK: 25,
      DEF: 9,
      quality: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Halberd',
      ATK: 27,
      DEF: 8,
      quality: 3,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'SVD',
      ATK: 70,
      DEF: 5,
      quality: 4,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Sombrero',
      ATK: 12,
      DEF: 10,
      quality: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Skewer',
      ATK: 15,
      DEF: 11,
      quality: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Blade Kusanagi',
      ATK: 90,
      DEF: 50,
      quality: 5,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Sock',
      ATK: 1,
      DEF: 2,
      quality: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'M1911',
      ATK: 40,
      DEF: 15,
      quality: 3,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'AC VAL',
      ATK: 45,
      DEF: 16,
      quality: 3,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'McMillan',
      ATK: 75,
      DEF: 14,
      quality: 4,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Two-handed sword',
      ATK: 66,
      DEF: 22,
      quality: 4,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Evil Mask of Shadows',
      ATK: 50,
      DEF: 90,
      quality: 5,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Ripped panties',
      ATK: 2,
      DEF: 5,
      quality: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Torn gloves',
      ATK: 4,
      DEF: 4,
      quality: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Kevlar gloves',
      ATK: 20,
      DEF: 35,
      quality: 3,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    ], {});
  },

  async down(queryInterface) {
    await queryInterface.bulkDelete('Weapons', null, {});
  },
};
