module.exports = {
  async up (queryInterface, Sequelize) {
     await queryInterface.bulkInsert('Users', [{
         username: 'test1',
         email: 'test1@test.ru',
         password: '12345678',
         createdAt: new Date(),
         updatedAt: new Date(),
     }, {
         username: 'tes2',
         email: 'test2@test.ru',
         password: '12345678',
         createdAt: new Date(),
         updatedAt: new Date(),
     }, {
         username: 'test3',
         email: 'test3@test.ru',
         password: '12345678',
         createdAt: new Date(),
         updatedAt: new Date(),
     }, {
         username: 'test4',
         email: 'test4@test.ru',
         password: '12345678',
         createdAt: new Date(),
         updatedAt: new Date(),
     }, {
         username: 'test5',
         email: 'test5@test.ru',
         password: '12345678',
         createdAt: new Date(),
         updatedAt: new Date(),
     }, {
         username: 'test6',
         email: 'test6@test.ru',
         password: '12345678',
         createdAt: new Date(),
         updatedAt: new Date(),
     }, {
         username: 'test7',
         email: 'test7@test.ru',
         password: '12345678',
         createdAt: new Date(),
         updatedAt: new Date(),
     }, {
         username: 'test8',
         email: 'test8@test.ru',
         password: '12345678',
         createdAt: new Date(),
         updatedAt: new Date(),
     }, {
         username: 'test9',
         email: 'test9@test.ru',
         password: '12345678',
         createdAt: new Date(),
         updatedAt: new Date(),
     }, {
         username: 'test10',
         email: 'test10@test.ru',
         password: '12345678',
         createdAt: new Date(),
         updatedAt: new Date(),
     }, {
         username: 'test11',
         email: 'test11@test.ru',
         password: '12345678',
         createdAt: new Date(),
         updatedAt: new Date(),
     }, {
         username: 'test12',
         email: 'test12@test.ru',
         password: '12345678',
         createdAt: new Date(),
         updatedAt: new Date(),
     }, {
         username: 'test13',
         email: 'test13@test.ru',
         password: '12345678',
         createdAt: new Date(),
         updatedAt: new Date(),
     }, {
         username: 'test14',
         email: 'test14@test.ru',
         password: '12345678',
         createdAt: new Date(),
         updatedAt: new Date(),
     }, {
         username: 'test15',
         email: 'test15@test.ru',
         password: '12345678',
         createdAt: new Date(),
         updatedAt: new Date(),
     }, {
         username: 'test16',
         email: 'test16@test.ru',
         password: '12345678',
         createdAt: new Date(),
         updatedAt: new Date(),
     }, {
         username: 'test17',
         email: 'test17@test.ru',
         password: '12345678',
         createdAt: new Date(),
         updatedAt: new Date(),
     }, {
         username: 'test18',
         email: 'test18@test.ru',
         password: '12345678',
         createdAt: new Date(),
         updatedAt: new Date(),
     }, {
         username: 'test19',
         email: 'test19@test.ru',
         password: '12345678',
         createdAt: new Date(),
         updatedAt: new Date(),
     }, {
         username: 'test20',
         email: 'test20@test.ru',
         password: '12345678',
         createdAt: new Date(),
         updatedAt: new Date(),
     }, {
         username: 'test21',
         email: 'test21@test.ru',
         password: '12345678',
         createdAt: new Date(),
         updatedAt: new Date(),
     }, {
         username: 'test22',
         email: 'test22@test.ru',
         password: '12345678',
         createdAt: new Date(),
         updatedAt: new Date(),
     }, {
         username: 'test23',
         email: 'test23@test.ru',
         password: '12345678',
         createdAt: new Date(),
         updatedAt: new Date(),
     }, {
         username: 'test24',
         email: 'test24@test.ru',
         password: '12345678',
         createdAt: new Date(),
         updatedAt: new Date(),
     }, {
         username: 'test25',
         email: 'test25@test.ru',
         password: '12345678',
         createdAt: new Date(),
         updatedAt: new Date(),
     }, {
         username: 'test26',
         email: 'test26@test.ru',
         password: '12345678',
         createdAt: new Date(),
         updatedAt: new Date(),
     }, {
         username: 'test27',
         email: 'test27@test.ru',
         password: '12345678',
         createdAt: new Date(),
         updatedAt: new Date(),
     }, {
         username: 'test28',
         email: 'test28@test.ru',
         password: '12345678',
         createdAt: new Date(),
         updatedAt: new Date(),
     }, {
         username: 'test29',
         email: 'test29@test.ru',
         password: '12345678',
         createdAt: new Date(),
         updatedAt: new Date(),
     }, {
         username: 'test30',
         email: 'test30@test.ru',
         password: '12345678',
         createdAt: new Date(),
         updatedAt: new Date(),
     }, {
         username: 'test31',
         email: 'test31@test.ru',
         password: '12345678',
         createdAt: new Date(),
         updatedAt: new Date(),
     }, {
         username: 'test32',
         email: 'test32@test.ru',
         password: '12345678',
         createdAt: new Date(),
         updatedAt: new Date(),
     }, {
         username: 'test33',
         email: 'test33@test.ru',
         password: '12345678',
         createdAt: new Date(),
         updatedAt: new Date(),
     }, {
         username: 'test34',
         email: 'test34@test.ru',
         password: '12345678',
         createdAt: new Date(),
         updatedAt: new Date(),
     }, {
         username: 'test35',
         email: 'test35@test.ru',
         password: '12345678',
         createdAt: new Date(),
         updatedAt: new Date(),
     }, {
         username: 'test36',
         email: 'test36@test.ru',
         password: '12345678',
         createdAt: new Date(),
         updatedAt: new Date(),
     }, {
         username: 'test37',
         email: 'test37@test.ru',
         password: '12345678',
         createdAt: new Date(),
         updatedAt: new Date(),
     }, {
         username: 'test38',
         email: 'test38@test.ru',
         password: '12345678',
         createdAt: new Date(),
         updatedAt: new Date(),
     }, {
         username: 'test39',
         email: 'test39@test.ru',
         password: '12345678',
         createdAt: new Date(),
         updatedAt: new Date(),
     }, {
         username: 'test40',
         email: 'test40@test.ru',
         password: '12345678',
         createdAt: new Date(),
         updatedAt: new Date(),
     }
     ], {});
  },

  async down (queryInterface, Sequelize) {
     await queryInterface.bulkDelete('Users', null, {});
  }
};
